-- データベース作成
DROP DATABASE IF EXISTS umadan;
CREATE DATABASE umadan;

-- データベース選択
USE umadan;
DROP USER IF EXISTS 'umadan'@'localhost';
CREATE USER 'umadan'@'localhost' IDENTIFIED BY 'umadan';
GRANT SELECT, INSERT ON umadan.* TO umadan@localhost;
SHOW GRANTS FOR 'umadan'@'localhost';

/*---------------テーブル作成----------------------*/

-- 的中
CREATE TABLE HIT (
    RACEDATE   DATE,
    COLLECT_PR INT(4) DEFAULT 0,
    HIT_PR     INT(4) DEFAULT 0,
    PRIMARY KEY(RACEDATE),
    CHECK(COLLECT_PR >= 0),
    CHECK(HIT_PR >= 0)
);

-- レース
CREATE TABLE RACE (
    RACE_ID     VARCHAR(12) ,
    RACEDATE    DATE NOT NULL,
    RNAME       VARCHAR(50) NOT NULL,
    RACENUMBER  INT(3) NOT NULL,
    TIME        TIME NOT NULL,
    DISTANCE    INT(4) NOT NULL,
    HORSE_TOTAL INT(2) NOT NULL,
    GROUND      VARCHAR(3) NOT NULL,
    PLACE       VARCHAR(2) NOT NULL,
    WEATHER     VARCHAR(3) NOT NULL,
    SPIN        VARCHAR(1) NOT NULL,
    SITUATION   VARCHAR(2) NOT NULL, 
    PRIMARY KEY(RACE_ID),
    FOREIGN KEY(RACEDATE) REFERENCES HIT(RACEDATE)
);

-- 結果情報
CREATE TABLE RESULT_HORSE (
    RACE_ID     VARCHAR(12) NOT NULL,
    HNAME       VARCHAR(9) NOT NULL,
    HORSENUMBER INT(2) NOT NULL,
    HORSEFRAME  INT(2) NOT NULL,
    RANKING     INT(1) NOT NULL,
    FOREIGN KEY(RACE_ID) REFERENCES RACE(RACE_ID),
    UNIQUE(HORSENUMBER , RANKING)
);

-- 予想情報
CREATE TABLE PREDICTION_HORSE (
    RACE_ID     VARCHAR(12) NOT NULL,
    HNAME       VARCHAR(9) NOT NULL,
    HORSENUMBER INT(2) NOT NULL,
    HORSEFRAME  INT(2) NOT NULL,
    RANKING     INT(1) NOT NULL,
    FOREIGN KEY(RACE_ID) REFERENCES RACE(RACE_ID),
    UNIQUE(HORSENUMBER , RANKING)
);

-- CREATE TABLE RESULT (
--     RACE_ID  VARCHAR(12) NOT NULL,
--     P1    VARCHAR(9) NOT NULL,    
--     P2    VARCHAR(9) NOT NULL,
--     P3    VARCHAR(9) NOT NULL,
--     P4    VARCHAR(9) NOT NULL,
--     P5    VARCHAR(9) NOT NULL,
--     R1    VARCHAR(9) NOT NULL,
--     R2    VARCHAR(9) NOT NULL,
--     R3    VARCHAR(9) NOT NULL,
--     R4    VARCHAR(9) NOT NULL,
--     R5    VARCHAR(9) NOT NULL,
--     FOREIGN KEY (RACE_ID) REFERENCES RACE(RACE_ID)
-- );

-- 払戻し詳細
CREATE TABLE HIT_DETAIL (
    RACE_ID     VARCHAR(12) NOT NULL,
    KINDS       VARCHAR(3) NOT NULL,
    HORSENUMBER INT(2) NOT NULL,
    HORSEFRAME  INT(2) NOT NULL,
    BETBACK     INT(8) NOT NULL DEFAULT 0,
    POPULAR     INT(2) NOT NULL,
    FOREIGN KEY(RACE_ID) REFERENCES RACE(RACE_ID),
    CHECK(BETBACK >= 0)
);

